# Используем базовый образ для Node.js
FROM node:14

# Устанавливаем зависимости для React
WORKDIR /app
COPY React/ml_app/package.json .
COPY React/ml_app/package-lock.json .
RUN npm install

# Копируем код React в контейнер
COPY React/ml_app /app

# Открываем порт, на котором будет работать React
EXPOSE 3000

# Запускаем React
CMD ["npm", "start"]
