# Используйте официальный образ Python
FROM python:3.9-slim

# Установите рабочую директорию
WORKDIR /app

# Скопируйте зависимости в контейнер
COPY FastAPI/requirements.txt /app/requirements.txt

# Скопируйте все файлы в контейнер
COPY FastAPI /app

# Установите зависимости
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

# Запустите ваше API
CMD ["python3", "main.py"]
